#!/usr/bin/env node
/**
 * Legacy Vite-era static asset generator.
 * Sitemap, robots.txt, and posts-index.json are now produced by Astro build (Phase 1).
 * This script is kept for reference only — not invoked by yarn build.
 */
console.log(
    '[static] Deprecated: sitemap/robots/posts-index are generated by astro build.'
);
